"""add_video_processing_status_fields

Revision ID: a207e77698e5
Revises: 
Create Date: 2025-11-01 20:04:23.952359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a207e77698e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add enum type
    videoprocessingstatus_enum = sa.Enum('SYNCED', 'AUDIO_DOWNLOADING', 'AUDIO_DOWNLOADED', 'TRANSCRIBING', 'TRANSCRIBED', 'INDEXING', 'COMPLETE', 'ERROR', name='videoprocessingstatus')
    videoprocessingstatus_enum.create(op.get_bind(), checkfirst=True)

    # Add column as nullable first to handle existing data
    op.add_column('videos', sa.Column('processing_status', videoprocessingstatus_enum, nullable=True))

    # Set default value for existing rows
    op.execute("UPDATE videos SET processing_status = 'SYNCED' WHERE processing_status IS NULL")

    # Make the column non-nullable
    op.alter_column('videos', 'processing_status', nullable=False, server_default='SYNCED')

    op.add_column('videos', sa.Column('processing_error', sa.Text(), nullable=True))
    op.add_column('videos', sa.Column('indexed_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'videos', 'channels', ['channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_column('videos', 'indexed_at')
    op.drop_column('videos', 'processing_error')
    op.drop_column('videos', 'processing_status')
    # ### end Alembic commands ###
